### ISSUE TITLE
InvalidCoordinates removing valid monitoring locations

### ISSUE THREAD

**Issue by anbethe** [USEPA/TADA#194]
The portion of WQPDataHarmonization.Rmd vignette that removes invalid coordinates, is removing one monitoring location from my dataset that has valid coordinates, in examining that location I cannot see why it's being filtered out. I've attached two data files that correspond with TADAProfile and TADAProfileClean1, 5 results for one monitoring location have been removed in TADAProfileClean1.

Here is the code: 
TADAProfile <- TADAdataRetrieval(ProjectIdentifier = "Anchorage Bacteria 20-21")

TADAProfileClean1 <- InvalidCoordinates(TADAProfile, clean_outsideUSA = 
                                          "remove", clean_imprecise = TRUE)

And the reprex:

``` r
TADAProfileClean1 <- InvalidCoordinates(TADAProfile, clean_outsideUSA = "remove", clean_imprecise = TRUE)
#> Error in InvalidCoordinates(TADAProfile, clean_outsideUSA = "remove", : could not find function "InvalidCoordinates"
```

<sup>Created on 2023-01-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
[TADAProfileClean1.xlsx](https://github.com/USEPA/TADA/files/10549013/TADAProfileClean1.xlsx)
[TADAProfile.xlsx](https://github.com/USEPA/TADA/files/10549015/TADAProfile.xlsx)

I'm new at this, let me know if I've missed anything!

**Comment by katiehealy** [comment]
@cristinamullin I was looking into this, and I think the issue is that the valid longitude coordinates for the site include a string of "999" (e.g. -149.8999650000). The InvalidCoordinates function weeds out any coordinates with that string assuming they are imprecise.

**Comment by cristinamullin** [comment]
@anbethe thanks for catching this bug! We will fix this on our end soon. For now, you can set clean_imprecise = FALSE so that this site is not removed from your dataset, e.g., TADAProfileClean1 <- InvalidCoordinates(TADAProfile, clean_outsideUSA = "remove", clean_imprecise = **FALSE**)

@katiehealy thanks for looking into this! To start, we could try updating our logic to only flag sites with 999 at the end of the string. We could also do some more research to see if there are any valid lat/longs that would have 999 at the end of the string. Alternatively, we could simply take this flag out, but it was designed to catch imprecise lat/longs where users just add a 999 or 9999 to the end of the lat/long to meet the WQX requirement for significant figures (when they don't know the precise coordinates). 

@laurashumway cc'ing your in case you have any suggestions regarding this issue/logic. Thanks!

**Comment by anbethe** [comment]
@katiehealy and @cristinamullin thanks so much for the feedback! I did double check and the coordinates were definitely valid, I'll use clean_imprecise = FALSE for now!

**Comment by cristinamullin** [comment]
Logic was removed from this function. Lat/longs with the string 999 will no longer be flagged.
