### ISSUE TITLE
TADAdataRetrieval function input name consistency with WQP UI, WQP Profiles, and dataRetrieval

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#196]
Background 

Cristina: TADAdataRetrieval uses "ProjectIdentifier" but dataRetrieval uses "project". Should we update all our inputs for consistency with dataRetrieval?

Elise H: It's a great question. I wonder what data submitters see in WQX when they upload a project ID. As a data user, I see the column names in the returned data profiles and it makes sense to me to have the function input match the column name on which I want to query. For example, I would be much more likely to know what a "ProjectIdentifier" input is, rather than "project". Similarly with "ActivityMediaName" rather than "sampleMedia". However, it is interesting that even the WQP browser interface is different. Continuing with these two examples, those fields are termed "Project ID" and "Sample Media" on the page itself. I think whichever we pick, adding documentation of field synonyms across querying platforms will make functions relatively simple to use (e.g. "project input is synonymous with the ProjectIdentifier column returned from the WQP and Project ID field on the web interface").

Cristina: For usability, I think it would be very helpful if there was consistency, but that might not be possible at this point since users are used to the current names. This may be a good point for a future WQP or WQX Team Discussion. Ideally, the name used would be consistent across the WQP UI, dataRetrieval, TADA, WQX, and the field headers included in the data profiles returned.

**Comment by cristinamullin** [comment]
@ldecicco-USGS Do you have any thoughts on this topic? Since we don't have a lot of users yet, we could use different names for our TADAdataRetrieval inputs (e.g. we currently use "ProjectIdentifier" but dataRetrieval uses "project") to potentially improve usability and consistency with what comes out in the profiles, or we could simply make our inputs consistent with dataRetrieval. You have a lot more experience working with users, is this an issue that comes up?

**Comment by ldecicco-USGS** [comment]
Just to make sure I understand the issue....

If you run some random query, you get ProjectIdentifier:

```r
DeWitt <- readWQPdata(
  statecode = "Illinois",
  countycode = "DeWitt",
  characteristicName = "Nitrogen"
)

"ProjectIdentifier" %in% names(DeWitt)
[1] TRUE
```

If you are trying to use the "Project" radio button:
![image](https://user-images.githubusercontent.com/1105215/216090981-4cea1541-5583-49a5-8002-e1d678a96dcc.png)

You would ask like this:
```r
project_data <- readWQPdata(
  statecode = "WI",
  countycode = "Dane",
  service = "Project"
)

"ProjectIdentifier" %in% names(project_data)
[1] TRUE

```

But here's where you all are discussing...

If you are querying by a specific ProjectIdentifier, dataRetrieval follows the WQP web services. The WQP UI tells us to ask for ProjectIdentifier by "project":

https://www.waterqualitydata.us/#project=000002.ER&mimeType=csv&dataProfile=resultPhysChem

click on the Advanced button and you will see the query is:
https://www.waterqualitydata.us/#project=000002.ER&mimeType=csv&dataProfile=resultPhysChem&providers=NWIS&providers=STEWARDS&providers=STORET

dataRetrieval therefore would get that data from:
```r
proj2 <- readWQPdata(project = "000002.ER")
```

1. One thing we can do in dataRetrieval is to add a simple "if the user asks for ProjectIdentifier, switch the URL to 'project' in the actual query" (we do that with a few things like site_no, so the users don't need to remember if they're in NWIS they call it site_no but if they're in WQP they call it siteid). This would keep things backwards compatible since if users _are_ using 'project' already, their code wouldn't break.

2. The other thing is to see if the WQP developers would want to change the web service queries. I doubt they'd agree to that - there are certainly other queries I can think of that use one word to query another. siteid for example is used to query MonitoringLocationIdentifier, you mentioned sample media above. There would be years of scripts that would break if they suddenly made the queries match the column headers. Plus, the developers probably did that to minimize URL size since browsers do enforce character limits. 


3. OR finally, TADA could follow the WQP web services and then we'd all be consistent.

I'm happy with 1 or 3, I just don't think we have the resources to even consider 2 at the point, and not sure if it would be a great idea since it would be pretty disruptive for long-time users.

So to be clear, dataRetrieval follows this:
https://www.waterqualitydata.us/data/swagger-ui/index.html

**Comment by ehinman** [comment]
Thanks for thinking on this topic a bit. After reading your response @ldecicco-USGS, I think it makes sense to match the TADA inputs with WQP web services. So, we would change ActivityMediaName to sampleMedia, ProjectIdentifier to project, and OrganizationIdentifier to organization. This is how Cristina coded the other inputs anyway: siteid, siteType, etc. to match what dataRetrieval accepts. As long as we have clear documentation in TADA about how those inputs map onto the WQP GUI and data profiles, hopefully users will not be too confused and there's less room in the function code for error. 

Might be a little ancillary: I noticed that we use the inputs startDate and endDate, which dataRetrieval accepts, but in the WQP web service call they are startDateLo and startDateHi. Was this change made to reduce confusion?

**Comment by ldecicco-USGS** [comment]
For the WQP calls, a user could use startDate OR startDateLo (and similarly endDate OR startDateHi). This is again because NWIS uses startDate. So, if a user is writing code to get discharge from NWIS and water quality stuff from WQP, they an have a sort of unified experience. But, if you are just doing WQP and have a good grasp of how the WQP works directly, you can still use those:

```r
secchi.names <- c(
  "Depth, Secchi disk depth",
  "Depth, Secchi disk depth (choice list)",
  "Secchi Reading Condition (choice list)",
  "Water transparency, Secchi disc"
)

df1 <-  readWQPdata(startDateLo = "2013-01-01",
                    startDateHi = "2013-12-31",
                    statecode = "WI",
                    characteristicName = secchi.names)

df2 <-  readWQPdata(startDate = "2013-01-01",
                    endDate = "2013-12-31",
                    statecode = "WI",
                    characteristicName = secchi.names)
range(df1$ActivityStartDate)
[1] "2013-01-10" "2013-12-12"
range(df2$ActivityStartDate)
[1] "2013-01-10" "2013-12-12"
```
