### ISSUE TITLE
DISSOLVED OXYGEN (DO) + % unit = INVALID

### ISSUE THREAD

**Issue by ehinman** [USEPA/TADA#318]
**Describe the bug**
Currently, the WQX QC validation table considers % and % SATURATN as Invalid result units for the Dissolved Oxygen (DO) characteristic name. This is a placeholder to discuss whether we want to address this issue in autoclean and replace the characteristic name with Dissolved oxygen saturation before unit flagging, leave as is, or find another solution.

Additional note: % SATURATN is an invalid unit for Dissolved oxygen saturation as well. This combo might also be present in NWIS data.

**Additional context**

**Reminders for TADA contributors addressing this issue**

New features should include all of the following work:

-   [ ] Create the function/code.

-   [ ] Document all code using comments to describe what is does.

-   [ ] Create tests in tests folder.

-   [ ] Create help file using roxygen2 above code.

-   [ ] Create working examples in help file (via roxygen2).

-   [ ] Add to appropriate vignette (or create new one).

**Comment by cristinamullin** [comment]
I like your idea of handling this in autoclean, before the flag functions would be run. I don't think there are a ton of other examples like this.

Alternatively, I remember creating a nonstandardized flag in the WQX validation table (in addition to valid/invalid). I think these ones should actually be marked as non-standardized, not invalid in the WQX validation table. Then I believe we only flag invalid combinations for removal, not non-standardized ones in the TADA flag functions, so these combos could then be handled in the TADA harmonization template?

Cristina A Mullin, PhD (she/her)
Water Data Integration Branch
Watershed Restoration, Assessment, and Protection Division
Office of Wetlands, Oceans and Watersheds
US EPA|Office of Water
***@***.******@***.***>

From: Elise H. ***@***.***>
Sent: Thursday, August 3, 2023 9:18 AM
To: USEPA/TADA ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [USEPA/TADA] DISSOLVED OXYGEN (DO) + % unit = INVALID (Issue #318)


Describe the bug
Currently, the WQX QC validation table considers % and % SATURATN as Invalid result units for the Dissolved Oxygen (DO) characteristic name. This is a placeholder to discuss whether we want to address this issue in autoclean and replace the characteristic name with Dissolved oxygen saturation before unit flagging, leave as is, or find another solution.

Additional note: % SATURATN is an invalid unit for Dissolved oxygen saturation as well. This combo might also be present in NWIS data.

Additional context

Add any other context about the problem here.

Reminders for TADA contributors addressing this issue

New features should include all of the following work:

  *   [ ] Create the function/code.
  *   [ ] Document all code using comments to describe what is does.
  *   [ ] Create tests in tests folder.
  *   [ ] Create help file using roxygen2 above code.
  *   [ ] Create working examples in help file (via roxygen2).
  *   [ ] Add to appropriate vignette (or create new one).

-
