### ISSUE TITLE
BigDataRetrieval Error

### ISSUE THREAD

**Issue by lettema** [USEPA/TADA#387]
Error with the function, trying to retrieve all enterococcus data in PA.  Based on error message, perhaps there is no data to retrieve?  Could use a message saying if that is the case.

RStudio 1.4.1106
R version 4.2.2 (2022-10-31 ucrt)

> library(tidyverse)
> library(lubridate)
> library(remotes)
> library(TADA)

> PAEnt<-TADA_BigDataRetrieval(
  startDate = "2018-01-01",
   endDate = "2023-12-31",
   characteristicName = c("Enterococcus"),
   statecode = c("PA"),
   applyautoclean = TRUE
 )
[1] "Building site summary table for chunking result downloads..."
[1] "Downloading data from sites with fewer than 250000 results by grouping them together."
[1] "Downloading WQP query results. This may take some time depending upon the query size."
 0s 0s 0sError in `dplyr::left_join()`:                                                            
 0s! `...` must be empty.
x Problematic argument:
* relationship = "many-to-many"

**Comment by cristinamullin** [comment]
Thanks @lettema... I recommend to use TADA_DataRetrieval because we have a few open issues related to TADA_BigDataRetrieval (I may remove that one as an exported function for now while we troubleshoot all of them). 

I double checked the WQP UI (www.waterqualitydata.us) and this query should return data (see download status below): 
Download Status
Your query will return 1,356 sample results from 49 sites:
From BIODATA: 0 sample results from 0 sites
From NWIS: 758 sample results from 28 sites
From STEWARDS: 0 sample results from 0 sites
From STORET: 598 sample results from 21 sites

TADA_DataRetrieval does work & doesn't take too long if you want to use that in the meantime: 
**`test = TADA_DataRetrieval(startDate = "2018-01-01", endDate = "2023-12-31", characteristicName = c("Enterococcus"), statecode = c("PA"), applyautoclean = TRUE)`**

**Comment by lettema** [comment]
Thanks!  I ran TADA_DataRetrieval and received the same error as I did previously.  

> datentPA<-TADA_DataRetrieval(
+   startDate = "2018-01-01",
+   endDate = "2023-12-31",
+   characteristicName = c("Enterococcus"),
+   statecode = c("PA"),
+   applyautoclean = TRUE
+ )
[1] "Downloading WQP query results. This may take some time depending upon the query size."
 0s 0sError in `dplyr::left_join()`:                                                            
 0s! `...` must be empty.
x Problematic argument:
* relationship = "many-to-many"
Run `rlang::last_trace()` to see where the error occurred.

**Comment by cristinamullin** [comment]
@lettema I just tried running this query with both TADA_DataRetrieval and TADA_BigDataRetrieval again but both are working for me so I am not able to reproduce the error. 

Can you try updating the TADA package and dependencies & then give it another try? Please let me know if that works or if you still see the same error. Thanks for your patience!

`remotes::install_github("USEPA/TADA", ref = "develop", dependencies = TRUE, force = TRUE)
`

**Comment by lettema** [comment]
@cristinamullin it turns out i had some issues with tidyverse dependencies not automatically loading/updating.  Once I fixed that, I was able to run it successfully.  Sorry about that!  Thanks for the support!
